In [2]:
import numpy as np

In [4]:
yhat = np.array([0,1,1,1,0,1,0])
y  = np.array([0.1,0.6,1,0.9,0.2,0.8,0])

In [5]:
def mae(yhat,y):
    total_error = 0
    for yp,yt in zip(yhat,y):
        total_error += abs(yt-yp)
    print('total_error:',total_error)
    mae = total_error/len(y)
    print('mae:',mae)
    return mae

In [6]:
mae(yhat,y)

total_error: 1.0
mae: 0.14285714285714285


0.14285714285714285

In [9]:
absolute_error = np.abs(y-yhat)
absolute_error

array([0.1, 0.4, 0. , 0.1, 0.2, 0.2, 0. ])

In [10]:
mean_abs_error = np.mean(absolute_error)
mean_abs_error

0.14285714285714285

In [11]:
np.log([0])

C:\Users\dasssvis\AppData\Local\Continuum\anaconda3\envs\vishal_env\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([-inf])

In [12]:
epsilon = 1e-10

In [19]:
yhat

array([0, 1, 1, 1, 0, 1, 0])

In [20]:
yhat_new = [max(i,epsilon) for i in yhat]
yhat_new

[1e-10, 1, 1, 1, 1e-10, 1, 1e-10]

In [21]:
yhat_new = [min(i,1-epsilon) for i in yhat_new]
yhat_new

[1e-10, 0.9999999999, 0.9999999999, 0.9999999999, 1e-10, 0.9999999999, 1e-10]

In [24]:
yhat_new = np.array(yhat_new)
yhat_new

array([1.e-10, 1.e+00, 1.e+00, 1.e+00, 1.e-10, 1.e+00, 1.e-10])

In [25]:
np.log(yhat_new)

array([-2.30258509e+01, -1.00000008e-10, -1.00000008e-10, -1.00000008e-10,
       -2.30258509e+01, -1.00000008e-10, -2.30258509e+01])

In [28]:
-np.mean(y*np.log(yhat_new) + (1-y)*np.log(1-yhat_new))

3.2894072675174573

The above expressions can be put together into a function

In [32]:
def log_loss(y,yhat):
    epsilon = 1e-10
    yhat_new = [max(i,epsilon) for i in yhat]
    yhat_new = [min(i,1-epsilon) for i in yhat_new]
    yhat_new = np.array(yhat_new)
    return (-np.mean(y*np.log(yhat_new)+(1-y)*np.log(1-yhat_new)))

In [33]:
log_loss(y,yhat)

3.2894072675174573

In [35]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [46]:
def mse(y_true,y_predicted):
    total_error = 0
    for yt,yp in zip(y_true,y_predicted):
        total_error += (yt-yp)**2
    print('Total Squared Error is :',total_error)
    mae = total_error/len(y_true)
    print('MAE',mae)
    return mse

In [47]:
mse(y_predicted,y_true)

Total Squared Error is : 1.83
MAE 0.366


<function __main__.mse(y_true, y_predicted)>

In [48]:
def mse(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        total_error += (yt-yp)**2
    print("Total Squared Error:",total_error)
    mse = total_error/len(y_true)
    print("Mean Squared Error:",mse)
    return mse

In [49]:
mse(y_predicted,y_true)

Total Squared Error: 1.83
Mean Squared Error: 0.366


0.366